// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJl1tYi7evKvQO0lxYqLwZ7rlAzRHE1o',
    appId: '1:458050746882:web:0d48171357a21c79e7451b',
    messagingSenderId: '458050746882',
    projectId: 'adaptorgames-d6e37',
    authDomain: 'adaptorgames-d6e37.firebaseapp.com',
    storageBucket: 'adaptorgames-d6e37.appspot.com',
    measurementId: 'G-E824X48JNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wAyhh4mnaW3rDQpWSlEjDhCg3uIf4jY',
    appId: '1:458050746882:android:6acffb079a1d6736e7451b',
    messagingSenderId: '458050746882',
    projectId: 'adaptorgames-d6e37',
    storageBucket: 'adaptorgames-d6e37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnDf0uorGRCH3r2hIzzM8M1eaYGF8tGJw',
    appId: '1:458050746882:ios:2074c56087e436abe7451b',
    messagingSenderId: '458050746882',
    projectId: 'adaptorgames-d6e37',
    storageBucket: 'adaptorgames-d6e37.appspot.com',
    iosBundleId: 'com.example.adaptorGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnDf0uorGRCH3r2hIzzM8M1eaYGF8tGJw',
    appId: '1:458050746882:ios:2074c56087e436abe7451b',
    messagingSenderId: '458050746882',
    projectId: 'adaptorgames-d6e37',
    storageBucket: 'adaptorgames-d6e37.appspot.com',
    iosBundleId: 'com.example.adaptorGames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGJl1tYi7evKvQO0lxYqLwZ7rlAzRHE1o',
    appId: '1:458050746882:web:6c73cf88421892dee7451b',
    messagingSenderId: '458050746882',
    projectId: 'adaptorgames-d6e37',
    authDomain: 'adaptorgames-d6e37.firebaseapp.com',
    storageBucket: 'adaptorgames-d6e37.appspot.com',
    measurementId: 'G-PF8NJQ8FD5',
  );
}
